import type { Metadata } from "next";
import GlobalProvider from "@/components/global-provider";
import "./globals.css";
import { cn } from "@/lib/utils";
import * as fonts from "@/lib/fonts";

export const metadata: Metadata = {
  title: "xbeats: music streaming",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          Object.values(fonts).map((font) => font.variable),
          "antialiased min-h-screen font-sans"
        )}
      >
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
